apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZWGxoYTJodmJuUTZaMmh3WDIweWNqVk1NbXhxWjI4MGVrMXZSa3hpYmpsV1owRm5TV0ZFTkc5Q2NqSnNOMGhpTlE9PSIKCQl9Cgl9LAoJImN1cnJlbnRDb250ZXh0IjogInJvb3RsZXNzIgp9Cg==
type: kubernetes.io/dockerconfigjson
