{{- if .Values.eventsService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: events-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.eventsService.replicas }}
  selector:
    matchLabels:
      app: events-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: events-service
    spec:
      containers:
      - name: events-service
        image: {{ .Values.eventsService.image.repository }}:{{ .Values.eventsService.image.tag }}
        imagePullPolicy: {{ .Values.eventsService.image.pullPolicy }}
        ports:
        - containerPort: 8082
        env:
        - name: PORT
          value: "8082"
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        resources:
          limits:
            cpu: {{ .Values.eventsService.resources.limits.cpu }}
            memory: {{ .Values.eventsService.resources.limits.memory }}
          requests:
            cpu: {{ .Values.eventsService.resources.requests.cpu }}
            memory: {{ .Values.eventsService.resources.requests.memory }}
        readinessProbe:
          httpGet:
            path: /api/events/health
            port: 8082
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/events/health
            port: 8082
          initialDelaySeconds: 15
          periodSeconds: 20
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: events-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: events-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: events-service
  ports:
  - port: {{ .Values.eventsService.service.port }}
    targetPort: {{ .Values.eventsService.service.targetPort }}
    protocol: TCP
  type: {{ .Values.eventsService.service.type }}
{{- end }}